export const doctorSpecializations = [
  { label: "Anestesiologi dan Terapi Intensif (Sp.An)", value: "Anestesiologi dan Terapi Intensif (Sp.An)" },
  { label: "Ilmu Bedah (Sp.B)", value: "Ilmu Bedah (Sp.B)" },
  { label: "Ilmu Penyakit Dalam (Sp.PD)", value: "Ilmu Penyakit Dalam (Sp.PD)" },
  { label: "Ilmu Kesehatan Anak (Sp.A)", value: "Ilmu Kesehatan Anak (Sp.A)" },
  { label: "Obstetri dan Ginekologi (Sp.OG)", value: "Obstetri dan Ginekologi (Sp.OG)" },
  { label: "Neurologi (Sp.N)", value: "Neurologi (Sp.N)" },
  { label: "Psikiatri (Sp.KJ)", value: "Psikiatri (Sp.KJ)" },
  { label: "Mata (Sp.M)", value: "Mata (Sp.M)" },
  { label: "Telinga Hidung Tenggorok Bedah Kepala Leher (Sp.THT-BKL)", value: "THT-BKL (Sp.THT-BKL)" },
  { label: "Dermatologi dan Venereologi (Sp.DV)", value: "Dermatologi dan Venereologi (Sp.DV)" },
  { label: "Kardiologi dan Kedokteran Vaskular (Sp.JP)", value: "Kardiologi dan Kedokteran Vaskular (Sp.JP)" },
  { label: "Pulmonologi dan Kedokteran Respirasi (Sp.P)", value: "Pulmonologi dan Kedokteran Respirasi (Sp.P)" },
  { label: "Ortopedi dan Traumatologi (Sp.OT)", value: "Ortopedi dan Traumatologi (Sp.OT)" },
  { label: "Urologi (Sp.U)", value: "Urologi (Sp.U)" },
  { label: "Bedah Saraf (Sp.BS)", value: "Bedah Saraf (Sp.BS)" },
  { label: "Bedah Plastik Rekonstruksi dan Estetik (Sp.BP-RE)", value: "Bedah Plastik (Sp.BP-RE)" },
  { label: "Bedah Toraks Kardiak dan Vaskular (Sp.BTKV)", value: "Bedah Toraks (Sp.BTKV)" },
  { label: "Radiologi (Sp.Rad)", value: "Radiologi (Sp.Rad)" },
  { label: "Patologi Anatomi (Sp.PA)", value: "Patologi Anatomi (Sp.PA)" },
  { label: "Patologi Klinik (Sp.PK)", value: "Patologi Klinik (Sp.PK)" },
  { label: "Rehabilitasi Medik (Sp.KFR)", value: "Rehabilitasi Medik (Sp.KFR)" },
  { label: "Gizi Klinik (Sp.GK)", value: "Gizi Klinik (Sp.GK)" },
  { label: "Kedokteran Olahraga (Sp.KO)", value: "Kedokteran Olahraga (Sp.KO)" },
  { label: "Kedokteran Forensik dan Medikolegal (Sp.FM)", value: "Kedokteran Forensik (Sp.FM)" },
  { label: "Kedokteran Penerbangan (Sp.KP)", value: "Kedokteran Penerbangan (Sp.KP)" },
  { label: "Kedokteran Okupasi (Sp.Ok)", value: "Kedokteran Okupasi (Sp.Ok)" },
  { label: "Mikrobiologi Klinik (Sp.MK)", value: "Mikrobiologi Klinik (Sp.MK)" },
  { label: "Parasitologi Klinik (Sp.ParK)", value: "Parasitologi Klinik (Sp.ParK)" },
  { label: "Farmakologi Klinik (Sp.FK)", value: "Farmakologi Klinik (Sp.FK)" }
];
